version: "3.8"
services:
  api:
    build: .
    container_name: social_backend_c
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mongo
    depends_on:
      - mongo

  database:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27018:27017'
    networks:
      - mongo
    volumes:
      - db:/data/db

networks:
  mongo:

volumes:
    db: